### ISSUE TITLE
给予建议

### ISSUE THREAD

**Issue by Night-GUA** [DuyeYa/NTOHER1#14]
将仓库名称改为NTOHER，并上传Releases版本，而并非代码
然后给我个开发者权限）

**Comment by LezaiYa** [comment]
> 将仓库名称改为NTOHER，并上传Releases版本，而并非代码 然后给我个开发者权限）

不是不想改，是天寸的库还没删，会重命名

**Comment by Night-GUA** [comment]
。。GitHub只要不是你自己的仓库重复就不会有提醒
